#!/usr/bin/env python3
"""Compute the execution order of the backlog and write it into docs/agents/PHASE1_EXECUTION.md.

A story's wave = 1 + the highest wave among its dependencies. Stories in the same wave don't depend on each
other, so they can run in parallel; a wave starts only when every story in the earlier waves is closed.

Usage:
  python3 scripts/backlog/waves.py            # rewrite the block between the waves markers
  python3 scripts/backlog/waves.py --check    # exit 1 if the doc is out of date (for CI)
  python3 scripts/backlog/waves.py --wave N   # one wave's stories with issue number, state and needs-human flag (uses gh)
  python3 scripts/backlog/waves.py --status   # open/closed per wave and the next wave to run (uses gh)
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STORIES = ROOT / "backlog" / "phase1" / "stories"
DOC = ROOT / "docs" / "agents" / "PHASE1_EXECUTION.md"
START, END = "<!-- waves:start -->", "<!-- waves:end -->"


def load() -> dict[str, dict]:
    stories = {}
    for f in sorted(STORIES.glob("*.md")):
        fm = re.match(r"(?s)^---\n(.*?)\n---\n", f.read_text())[1]

        def field(k: str) -> str:
            return re.search(rf"^{k}: (.*)$", fm, re.M)[1]

        stories[field("id")] = {
            "title": json.loads(field("title")),
            "size": field("size"),
            "deps": json.loads(field("depends")),
            "labels": json.loads(field("labels")),
        }
    return stories


def order_key(story_id: str) -> tuple[int, int]:
    epic, num = story_id.split("-")
    return int(epic[1:]), int(num)


def waves(stories: dict[str, dict]) -> dict[int, list[str]]:
    level: dict[str, int] = {}

    def visit(n: str, path: tuple[str, ...] = ()) -> int:
        if n in path:
            raise SystemExit(f"dependency cycle: {' -> '.join(path + (n,))}")
        if n not in level:
            level[n] = 1 + max((visit(d, path + (n,)) for d in stories[n]["deps"]), default=0)
        return level[n]

    for n in stories:
        visit(n)
    out: dict[int, list[str]] = {}
    for n, lv in level.items():
        out.setdefault(lv, []).append(n)
    return {k: sorted(v, key=order_key) for k, v in sorted(out.items())}


def render(stories: dict[str, dict]) -> str:
    w = waves(stories)
    lines = [
        START,
        "<!-- Generated by scripts/backlog/waves.py. Don't edit by hand. -->",
        "",
        f"**{len(stories)} stories in {len(w)} waves.** Run the waves in order; the stories inside a wave can run in parallel.",
        "🧑 = `needs-human`: an agent prepares what it can, then hands over to a person.",
        "",
        "| Wave | Parallel stories | Count |",
        "|---|---|---|",
    ]
    for lv, ids in w.items():
        cells = ", ".join(f"{'🧑 ' if 'needs-human' in stories[i]['labels'] else ''}`{i}`" for i in ids)
        lines.append(f"| {lv} | {cells} | {len(ids)} |")
    lines += ["", "<details><summary>Every story with its dependencies</summary>", "",
              "| Wave | Story | Size | Title | Depends on |", "|---|---|---|---|---|"]
    for lv, ids in w.items():
        for i in ids:
            s = stories[i]
            deps = ", ".join(s["deps"]) or "—"
            human = " 🧑" if "needs-human" in s["labels"] else ""
            lines.append(f"| {lv} | `{i}`{human} | {s['size']} | {s['title']} | {deps} |")
    lines += ["", "</details>", END]
    return "\n".join(lines)


def issue_states() -> dict[str, dict]:
    """Story id -> {number, state} from GitHub (titles start with "[Mx-yy]")."""
    out = subprocess.run(
        ["gh", "issue", "list", "--repo", "dculussoftwares/stayfocus", "--state", "all", "--limit", "300",
         "--label", "type:story", "--json", "number,title,state"],
        check=True, capture_output=True, text=True,
    ).stdout
    states = {}
    for issue in json.loads(out):
        m = re.match(r"^\[(M\d+-\d+)\]", issue["title"])
        if m:
            states[m[1]] = {"number": issue["number"], "state": issue["state"]}
    return states


def print_wave(n: int) -> None:
    stories = load()
    ids = waves(stories).get(n)
    if not ids:
        raise SystemExit(f"no wave {n}")
    states = issue_states()
    for i in ids:
        st = states.get(i, {"number": "?", "state": "MISSING"})
        human = "needs-human" if "needs-human" in stories[i]["labels"] else ""
        deps = ",".join(stories[i]["deps"]) or "-"
        print(f"{i}\t#{st['number']}\t{st['state']}\t{stories[i]['size']}\t{human or '-'}\tdeps={deps}\t{stories[i]['title']}")


def print_status() -> None:
    stories = load()
    states = issue_states()
    next_wave = None
    for lv, ids in waves(stories).items():
        open_ids = [i for i in ids if states.get(i, {}).get("state") != "CLOSED"]
        if open_ids and next_wave is None:
            next_wave = lv
        print(f"wave {lv:>2}: {len(ids) - len(open_ids)}/{len(ids)} closed" + (f"  open: {', '.join(open_ids)}" if open_ids else ""))
    print(f"NEXT_WAVE={next_wave if next_wave is not None else 'done'}")


def main() -> None:
    if "--wave" in sys.argv:
        print_wave(int(sys.argv[sys.argv.index("--wave") + 1]))
        return
    if "--status" in sys.argv:
        print_status()
        return
    block = render(load())
    doc = DOC.read_text()
    new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, doc, flags=re.S)
    if "--check" in sys.argv:
        if new != doc:
            raise SystemExit("docs/agents/PHASE1_EXECUTION.md is out of date: run python3 scripts/backlog/waves.py")
        print("waves up to date")
        return
    DOC.write_text(new)
    print(f"updated {DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
