#!/usr/bin/env python3
"""Compute the execution order of the backlog and write it into docs/agents/PHASE1_EXECUTION.md.

A story's wave = 1 + the highest wave among its dependencies. Stories in the same wave don't depend on each
other, so they can run in parallel; a wave starts only when every story in the earlier waves is closed.

Usage:
  python3 scripts/backlog/waves.py            # rewrite the block between the waves markers
  python3 scripts/backlog/waves.py --check    # exit 1 if the doc is out of date (for CI)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STORIES = ROOT / "backlog" / "phase1" / "stories"
DOC = ROOT / "docs" / "agents" / "PHASE1_EXECUTION.md"
START, END = "<!-- waves:start -->", "<!-- waves:end -->"


def load() -> dict[str, dict]:
    stories = {}
    for f in sorted(STORIES.glob("*.md")):
        fm = re.match(r"(?s)^---\n(.*?)\n---\n", f.read_text())[1]

        def field(k: str) -> str:
            return re.search(rf"^{k}: (.*)$", fm, re.M)[1]

        stories[field("id")] = {
            "title": json.loads(field("title")),
            "size": field("size"),
            "deps": json.loads(field("depends")),
            "labels": json.loads(field("labels")),
        }
    return stories


def order_key(story_id: str) -> tuple[int, int]:
    epic, num = story_id.split("-")
    return int(epic[1:]), int(num)


def waves(stories: dict[str, dict]) -> dict[int, list[str]]:
    level: dict[str, int] = {}

    def visit(n: str, path: tuple[str, ...] = ()) -> int:
        if n in path:
            raise SystemExit(f"dependency cycle: {' -> '.join(path + (n,))}")
        if n not in level:
            level[n] = 1 + max((visit(d, path + (n,)) for d in stories[n]["deps"]), default=0)
        return level[n]

    for n in stories:
        visit(n)
    out: dict[int, list[str]] = {}
    for n, lv in level.items():
        out.setdefault(lv, []).append(n)
    return {k: sorted(v, key=order_key) for k, v in sorted(out.items())}


def render(stories: dict[str, dict]) -> str:
    w = waves(stories)
    lines = [
        START,
        "<!-- Generated by scripts/backlog/waves.py. Don't edit by hand. -->",
        "",
        f"**{len(stories)} stories in {len(w)} waves.** Run the waves in order; the stories inside a wave can run in parallel.",
        "🧑 = `needs-human`: an agent prepares what it can, then hands over to a person.",
        "",
        "| Wave | Parallel stories | Count |",
        "|---|---|---|",
    ]
    for lv, ids in w.items():
        cells = ", ".join(f"{'🧑 ' if 'needs-human' in stories[i]['labels'] else ''}`{i}`" for i in ids)
        lines.append(f"| {lv} | {cells} | {len(ids)} |")
    lines += ["", "<details><summary>Every story with its dependencies</summary>", "",
              "| Wave | Story | Size | Title | Depends on |", "|---|---|---|---|---|"]
    for lv, ids in w.items():
        for i in ids:
            s = stories[i]
            deps = ", ".join(s["deps"]) or "—"
            human = " 🧑" if "needs-human" in s["labels"] else ""
            lines.append(f"| {lv} | `{i}`{human} | {s['size']} | {s['title']} | {deps} |")
    lines += ["", "</details>", END]
    return "\n".join(lines)


def main() -> None:
    block = render(load())
    doc = DOC.read_text()
    new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, doc, flags=re.S)
    if "--check" in sys.argv:
        if new != doc:
            raise SystemExit("docs/agents/PHASE1_EXECUTION.md is out of date: run python3 scripts/backlog/waves.py")
        print("waves up to date")
        return
    DOC.write_text(new)
    print(f"updated {DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
